version: 2

models:
  - name: dim_date
    columns:
      - name: date_key
        tests:
          - unique
          - not_null

  - name: dim_provider
    columns:
      - name: provider_key
        tests:
          - unique
          - not_null

  - name: dim_vehicle
    columns:
      - name: vehicle_key
        tests:
          - unique
          - not_null
      - name: vehicle_class
        tests:
          - not_null

  - name: dim_orbit